// Generated by gencpp from file lab_4/lab_4.msg
// DO NOT EDIT!


#ifndef LAB_4_MESSAGE_LAB_4_H
#define LAB_4_MESSAGE_LAB_4_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab_4
{
template <class ContainerAllocator>
struct lab_4_
{
  typedef lab_4_<ContainerAllocator> Type;

  lab_4_()
    : map(0)  {
    }
  lab_4_(const ContainerAllocator& _alloc)
    : map(0)  {
  (void)_alloc;
    }



   typedef int32_t _map_type;
  _map_type map;





  typedef boost::shared_ptr< ::lab_4::lab_4_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab_4::lab_4_<ContainerAllocator> const> ConstPtr;

}; // struct lab_4_

typedef ::lab_4::lab_4_<std::allocator<void> > lab_4;

typedef boost::shared_ptr< ::lab_4::lab_4 > lab_4Ptr;
typedef boost::shared_ptr< ::lab_4::lab_4 const> lab_4ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab_4::lab_4_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab_4::lab_4_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab_4::lab_4_<ContainerAllocator1> & lhs, const ::lab_4::lab_4_<ContainerAllocator2> & rhs)
{
  return lhs.map == rhs.map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab_4::lab_4_<ContainerAllocator1> & lhs, const ::lab_4::lab_4_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab_4

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab_4::lab_4_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab_4::lab_4_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_4::lab_4_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_4::lab_4_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_4::lab_4_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_4::lab_4_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab_4::lab_4_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9d42f357b4ccb74b79f4d7ca1e324a6";
  }

  static const char* value(const ::lab_4::lab_4_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9d42f357b4ccb74ULL;
  static const uint64_t static_value2 = 0xb79f4d7ca1e324a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab_4::lab_4_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab_4/lab_4";
  }

  static const char* value(const ::lab_4::lab_4_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab_4::lab_4_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 map \n"
;
  }

  static const char* value(const ::lab_4::lab_4_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab_4::lab_4_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lab_4_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab_4::lab_4_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab_4::lab_4_<ContainerAllocator>& v)
  {
    s << indent << "map: ";
    Printer<int32_t>::stream(s, indent + "  ", v.map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB_4_MESSAGE_LAB_4_H
