// Generated by gencpp from file Lab2/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LAB2_MESSAGE_ADDTWOINTS_H
#define LAB2_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <Lab2/AddTwoIntsRequest.h>
#include <Lab2/AddTwoIntsResponse.h>


namespace Lab2
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace Lab2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Lab2::AddTwoInts > {
  static const char* value()
  {
    return "6ca82c4161f4882477f038fb04881451";
  }

  static const char* value(const ::Lab2::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::Lab2::AddTwoInts > {
  static const char* value()
  {
    return "Lab2/AddTwoInts";
  }

  static const char* value(const ::Lab2::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::Lab2::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::Lab2::AddTwoInts >
template<>
struct MD5Sum< ::Lab2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Lab2::AddTwoInts >::value();
  }
  static const char* value(const ::Lab2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Lab2::AddTwoIntsRequest> should match
// service_traits::DataType< ::Lab2::AddTwoInts >
template<>
struct DataType< ::Lab2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::Lab2::AddTwoInts >::value();
  }
  static const char* value(const ::Lab2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Lab2::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::Lab2::AddTwoInts >
template<>
struct MD5Sum< ::Lab2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Lab2::AddTwoInts >::value();
  }
  static const char* value(const ::Lab2::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Lab2::AddTwoIntsResponse> should match
// service_traits::DataType< ::Lab2::AddTwoInts >
template<>
struct DataType< ::Lab2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::Lab2::AddTwoInts >::value();
  }
  static const char* value(const ::Lab2::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB2_MESSAGE_ADDTWOINTS_H
