// Generated by gencpp from file Lab2/Age.msg
// DO NOT EDIT!


#ifndef LAB2_MESSAGE_AGE_H
#define LAB2_MESSAGE_AGE_H

#include <ros/service_traits.h>


#include <Lab2/AgeRequest.h>
#include <Lab2/AgeResponse.h>


namespace Lab2
{

struct Age
{

typedef AgeRequest Request;
typedef AgeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Age
} // namespace Lab2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Lab2::Age > {
  static const char* value()
  {
    return "a149e0d1d17f6cb7129d50d2ec76d5e8";
  }

  static const char* value(const ::Lab2::Age&) { return value(); }
};

template<>
struct DataType< ::Lab2::Age > {
  static const char* value()
  {
    return "Lab2/Age";
  }

  static const char* value(const ::Lab2::Age&) { return value(); }
};


// service_traits::MD5Sum< ::Lab2::AgeRequest> should match
// service_traits::MD5Sum< ::Lab2::Age >
template<>
struct MD5Sum< ::Lab2::AgeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Lab2::Age >::value();
  }
  static const char* value(const ::Lab2::AgeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Lab2::AgeRequest> should match
// service_traits::DataType< ::Lab2::Age >
template<>
struct DataType< ::Lab2::AgeRequest>
{
  static const char* value()
  {
    return DataType< ::Lab2::Age >::value();
  }
  static const char* value(const ::Lab2::AgeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Lab2::AgeResponse> should match
// service_traits::MD5Sum< ::Lab2::Age >
template<>
struct MD5Sum< ::Lab2::AgeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Lab2::Age >::value();
  }
  static const char* value(const ::Lab2::AgeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Lab2::AgeResponse> should match
// service_traits::DataType< ::Lab2::Age >
template<>
struct DataType< ::Lab2::AgeResponse>
{
  static const char* value()
  {
    return DataType< ::Lab2::Age >::value();
  }
  static const char* value(const ::Lab2::AgeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB2_MESSAGE_AGE_H
